############################################
# Github Action Workflow to poll and aggregate logs #
############################################
name: POLL/POST Audit Log Data from V4 API

##############################################
# Run once an hour and when pushed to main #
##############################################
on:
  push:
    branches: master
  schedule:
    - cron: '00 15 * * 0'

#################
# Build the job #
#################
jobs:
  poll:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # Clone source code
    - name: Checkout source code
      uses: actions/checkout@v2

    # Install congiure NodeJS
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Need to install NPM
    - name: NPM Install
      run: npm install

      # If this is the first time we poll, then do a fresh poll. If not, poll from latest cursor.
    - name: Poll from Cursor
      run: |
        if [ -f ".last-cursor-update" ]; then
          LAST_CURSOR=$(cat .last-cursor-update)
        fi
        if [ -z "$LAST_CURSOR" ]; then
          echo "FIRST TIME RUNNING AUDIT LOG POLL"
        #  npm start -- --token ${{secrets.AUDIT_LOG_TOKEN}} --org ${{secrets.ORG_NAME}} --file 'audit-log-output.json'
        else
          echo "RUNNING AUDIT LOG POLL FROM $LAST_CURSOR"
        #  npm start -- --token ${{secrets.AUDIT_LOG_TOKEN}} --org ${{secrets.ORG_NAME}} --cursor $LAST_CURSOR --file 'audit-log-output.json'
        fi

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/ #myapp

        #curl -X POST -H "Content-Type: application/json" -d @audit-log-output.json ${{secrets.WEBHOOK_URL}}
        #curl -X POST -H "Content-Type: application/json" -d '{"text":"Webhook test"}' ${{secrets.WEBHOOK_URL}}
        #curl -X POST ${{secrets.WEBHOOK_URL}} -H "Content-Type: application/json" -d '{"text":"a0あああああああああ99あああああああああ98あああああああああ97あああああああああ96あああああああああ95あああああああああ94あああああああああ93あああああああああ92あああああああああ91あああああああああ90あああああああああ89あああああああああ88あああああああああ87あああああああああ86あああああああああ85あああああああああ84あああああああああ83あああああああああ82あああああああああ81あああああああああ80あああああああああ79あああああああああ78あああああああああ77あああああああああ76あああああああああ75あああああああああ74あああああああああ73あああああああああ72あああああああああ71あああああああああ70あああああああああ69あああああああああ68あああああああああ67あああああああああ66あああああああああ65あああああああああ64あああああああああ63あああああああああ62あああああああああ61あああああああああ60あああああああああ59あああああああああ58あああああああああ57あああああああああ56あああああああああ55あああああああああ54あああああああああ53あああああああああ52あああああああああ51あああああああああ50あああああああああ49あああああああああ48あああああああああ47あああああああああ46あああああああああ45あああああああああ44あああああああああ43あああああああああ42あああああああああ41あああああああああ40あああああああああ39あああああああああ38あああああああああ37あああああああああ36あああああああああ35あああああああああ34あああああああああ33あああああああああ32あああああああああ31あああああああああ30あああああああああ29あああああああああ28あああああああああ27あああああああああ26あああああああああ25あああああああああ24あああああああああ23あああああああああ22あああああああああ21あああああああああ20あああああああああ19あああああああああ18あああああああああ17あああああああああ16あああああああああ15あああああああああ14あああああああああ13あああああああああ12あああああああああ11あああああああああ10あああああああああ09あああああああああ08あああああああああ07あああああああああ06あああああああああ05あああああああああ04あああああああああ03あああああああああ02あああああああああ01あああああああああa0あああああああああ99あああああああああ98あああああああああ97あああああああああ96あああああああああ95あああああああああ94あああああああああ93あああああああああ92あああああああああ91あああああああああ90あああああああああ89あああああああああ88あああああああああ87あああああああああ86あああああああああ85あああああああああ84あああああああああ83あああああああああ82あああああああああ81あああああああああ80あああああああああ79あああああああああ78あああああああああ77あああああああああ76あああああああああ75あああああああああ74あああああああああ73あああああああああ72あああああああああ71あああああああああ70あああああああああ69あああああああああ68あああああああああ67あああああああああ66あああああああああ65あああああああああ64あああああああああ63あああああああああ62あああああああああ61あああああああああ60あああああああああ59あああああああああ58あああああああああ57あああああああああ56あああああああああ55あああああああああ54あああああああああ53あああああああああ52あああああああああ51あああああああああ50あああああああああ49あああああああああ48あああああああああ47あああああああああ46あああああああああ45あああああああああ44あああああああああ43あああああああああ42あああああああああ41あああああああああ40あああああああああ39あああああああああ38あああああああああ37あああああああああ36あああああああああ35あああああああああ34あああああああああ33あああああああああ32あああああああああ31あああああああああ30あああああああああ29あああああああああ28あああああああああ27あああああああああ26あああああああああ25あああああああああ24あああああああああ23あああああああああ22あああああああああ21あああああああああ20あああああああああ19あああああああああ18あああああああああ17あああああああああ16あああああああああ15あああああああああ14あああああああああ13あああああああああ12あああああああああ11あああああああああ10あああああああああ09あああああああああ08あああああああああ07あああああああああ06あああああああああ05あああああああああ04あああああああああ03あああああああああ02あああああああああ01あああああああああa0あああああああああ99あああああああああ98あああああああああ97あああああああああ96あああああああああ95あああああああああ94あああああああああ93あああああああああ92あああああああああ91あああああああああ90あああああああああ89あああああああああ88あああああああああ87あああああああああ86あああああああああ85あああああああああ84あああああああああ83あああああああああ82あああああああああ81あああああああああ80あああああああああ79あああああああああ78あああああああああ77あああああああああ76あああああああああ75あああああああああ74あああああああああ73あああああああああ72あああああああああ71あああああああああ70あああああああああ69あああああああああ68あああああああああ67あああああああああ66あああああああああ65あああああああああ64あああああああああ63あああああああああ62あああああああああ61あああああああああ60あああああああああ59あああああああああ58あああああああああ57あああああああああ56あああああああああ55あああああああああ54あああああああああ53あああああああああ52あああああああああ51あああああああああ50あああああああああ49あああああああああ48あああああああああ47あああああああああ46あああああああああ45あああああああああ44あああああああああ43あああああああああ42あああああああああ41あああああああああ40あああああああああ39あああああああああ38あああああああああ37あああああああああ36あああああああああ35あああああああああ34あああああああああ33あああああああああ32あああああああああ31あああああああああ30あああああああああ29あああああああああ28あああああああああ27あああああああああ26あああああああああ25あああああああああ24あああああああああ23あああああああああ22あああああああああ21あああああああああ20あああああああああ19あああああああああ18あああああああああ17あああああああああ16あああああああああ15あああああああああ14あああああああああ13あああああああああ12あああああああああ11あああああああああ10あああああああああ09あああああああああ08あああああああああ07あああああああああ06あああああああああ05あああああああああ04あああああああああ03あああああああああ02あああああああああ01あああああああああa0あああああああああ99あああああああああ98あああああああああ97あああああああああ96あああああああああ95あああああああああ94あああああああああ93あああああああああ92あああああああああ91あああああああああ90あああああああああ89あああああああああ88あああああああああ87あああああああああ86あああああああああ85あああああああああ84あああああああああ83あああああああああ82あああああああああ81あああああああああ80あああああああああ79あああああああああ78あああああああああ77あああああああああ76あああああああああ75あああああああああ74あああああああああ73あああああああああ72あああああああああ71あああああああああ70あああああああああ69あああああああああ68あああああああああ67あああああああああ66あああああああああ65あああああああああ64あああああああああ63あああああああああ62あああああああああ61あああああああああ60あああああああああ59あああああああああ58あああああああああ57あああああああああ56あああああああああ55あああああああああ54あああああああああ53あああああああああ52あああああああああ51あああああああああ50あああああああああ49あああああああああ48あああああああああ47あああああああああ46あああああああああ45あああああああああ44あああああああああ43あああああああああ42あああああああああ41あああああああああ40あああああああああ39あああああああああ38あああああああああ37あああああああああ36あああああああああ35あああああああああ34あああああああああ33あああああああああ32あああああああああ31あああああああああ30あああああああああ29あああああああああ28あああああああああ27あああああああああ26あああああああああ25あああああああああ24あああああああああ23あああああああああ22あああああああああ21あああああああああ20あああああああああ19あああああああああ18あああああああああ17あああああああああ16あああああああああ15あああああああああ14あああああああああ13あああああああああ12あああああああああ11あああああああああ10あああああああああ09あああああああああ08あああああああああ07あああああああああ06あああああああああ05あああああああああ04あああああああああ03あああああああああ02あああああああああ01あああああああああ"}'

    # Commit the cursor back to source
    - name: Commit cursor
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Audit Log Integration
        author_email: ${{ secrets.COMMITTER_EMAIL }}
        message: "Updating cursor for audit log"
        add: ".last-cursor-update --force"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
